<a href="https://colab.research.google.com/github/stefanporosanu/Python-Pandas-Projects/blob/main/Global-Superstore-Data-Exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel("/content/work today.xlsx")

/usr/local/lib/python3.13/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.13/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544,40.77,High
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  object
 2   Order Date      51290 non-null  datetime64[ns]
 3   Ship Date       51290 non-null  datetime64[ns]
 4   Ship Mode       51290 non-null  object
 5   Customer ID     51290 non-null  object
 6   Customer Name   51290 non-null  object
 7   Segment         51290 non-null  object
 8   Postal Code     9994 non-null   float64
 9   City            51290 non-null  object
 10  State           51290 non-null  object
 11  Country         51290 non-null  object
 12  Region          51290 non-null  object
 13  Market          51290 non-null  object
 14  Product ID      51290 non-null  object
 15  Category        51290 non-null  object
 16  Sub-Category    51290 non-null  object
 17  Product Name    51290 non-null  object
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  object
dtypes: datetime64[ns](2), float64(5), int64(2), object(15)
memory usage: 9.4+ MB

Postal code has missing values

In [ ]:
df.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit,Shipping Cost
count,51290.00000,51290,51290,9994.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000
mean,25645.50000,2014-05-11 21:26:49.155780608,2014-05-15 20:42:42.745174528,55190.379428,246.490581,3.476545,0.142908,28.610982,26.478567
min,1.00000,2012-01-01 00:00:00,2012-01-03 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000,1.002000
25%,12823.25000,2013-06-19 00:00:00,2013-06-23 00:00:00,23223.000000,30.758625,2.000000,0.000000,0.000000,2.610000
50%,25645.50000,2014-07-08 00:00:00,2014-07-12 00:00:00,56430.500000,85.053000,3.000000,0.000000,9.240000,7.790000
75%,38467.75000,2015-05-22 00:00:00,2015-05-26 00:00:00,90008.000000,251.053200,5.000000,0.200000,36.810000,24.450000
max,51290.00000,2015-12-31 00:00:00,2016-01-07 00:00:00,99301.000000,22638.480000,14.000000,0.850000,8399.976000,933.570000
std,14806.29199,NaN,NaN,32063.693350,487.565361,2.278766,0.212280,174.340972,57.251373

In [ ]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
51285,29002,IN-2015-KE1642066-42174,2015-06-19,2015-06-19,Same Day,KE-1642066,Katrina Edelman,Corporate,NaN,Kure,...,OFF-FA-3072,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.10,5,0.0,4.5000,1.010,Medium
51286,34337,US-2014-ZD21925140-41765,2014-05-06,2014-05-10,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,FUR-FU-4070,Furniture,Furnishings,"Eldon Image Series Desk Accessories, Burgundy",16.72,5,0.2,3.3440,1.930,High
51287,31315,CA-2012-ZD21925140-41147,2012-08-26,2012-08-31,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,OFF-AR-5321,Office Supplies,Art,Newell 341,8.56,2,0.0,2.4824,1.580,High
51288,9596,MX-2013-RB1979518-41322,2013-02-17,2013-02-21,Standard Class,RB-1979518,Ross Baird,Home Office,NaN,Valinhos,...,OFF-BI-2919,Office Supplies,Binders,"Acco Index Tab, Economy",13.44,2,0.0,2.4000,1.003,Medium
51289,6147,MX-2013-MC1810093-41416,2013-05-22,2013-05-26,Second Class,MC-1810093,Mick Crebagga,Consumer,NaN,Tipitapa,...,OFF-PA-3990,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.38,3,0.0,1.8000,1.002,High

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Postal Code', 'City',
       'State', 'Country', 'Region', 'Market', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority'],
      dtype='object')

In [ ]:
df.isnull().sum()

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
Postal Code       41296
City                  0
State                 0
Country               0
Region                0
Market                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

In [ ]:
df["Postal Code"].isnull().sum()

np.int64(41296)

In [ ]:
df["Ship Mode"].value_counts()

Ship Mode
Standard Class    30775
Second Class      10309
First Class        7505
Same Day           2701
Name: count, dtype: int64

In [ ]:
df.loc[df["Country"]=="Bulgaria", ["Customer Name", "Segment", "Product Name", "Category"]]

,Customer Name,Segment,Product Name,Category
1336,Pamela Coakley,Corporate,"Safco Library with Doors, Pine",Furniture
2020,Christina Anderson,Consumer,"StarTech Inkjet, Wireless",Technology
2272,Deanra Eno,Home Office,"Apple Smart Phone, Cordless",Technology
6041,Jas O'Carroll,Consumer,"Safco Corner Shelving, Mobile",Furniture
6897,Valerie Takahito,Home Office,"Eldon File Cart, Single Width",Office Supplies
...,...,...,...,...
48453,Pamela Coakley,Corporate,"Wilson Jones Hole Reinforcements, Clear",Office Supplies
49036,Aaron Hawkins,Corporate,"GlobeWeis Business Envelopes, Set of 50",Office Supplies
49497,Pamela Coakley,Corporate,"Wilson Jones Binder, Recycled",Office Supplies
50107,Thomas Thornton,Consumer,"Acco Hole Reinforcements, Clear",Office Supplies
50966,Hallie Redmond,Home Office,"Boston Pens, Blue",Office Supplies

In [ ]:
df.loc[df["City"]=="Istanbul", ["Customer Name", "Segment", "Product Name", "Category"]]

,Customer Name,Segment,Product Name,Category
725,Cynthia Voltz,Corporate,"Harbour Creations Executive Leather Armchair, ...",Furniture
2420,Muhammed Yedwab,Corporate,"Dania Library with Doors, Metal",Furniture
3261,Chad Sievert,Consumer,"Harbour Creations Swivel Stool, Adjustable",Furniture
3856,Bobby Trafton,Consumer,"Dania Library with Doors, Mobile",Furniture
4611,Pete Kriz,Consumer,"Samsung Smart Phone, VoIP",Technology
...,...,...,...,...
50890,Greg Guthrie,Corporate,"Avery 3-Hole Punch, Recycled",Office Supplies
50981,Kristen Hastings,Corporate,"Eldon Trays, Wire Frame",Office Supplies
51002,Sean Wendt,Home Office,"Wilson Jones Binding Machine, Economy",Office Supplies
51026,Barry Pond,Corporate,"Fellowes Box, Single Width",Office Supplies
51201,Joni Blumstein,Consumer,"Advantus Paper Clips, Assorted Sizes",Office Supplies

In [ ]:
df[df["Country"]=="United Kingdom"]["Sales"].mean()

np.float64(323.68420085731776)

In [ ]:
df["Profit"].nlargest(3)

49003    8399.9760
44248    6719.9808
25238    5039.9856
Name: Profit, dtype: float64

In [ ]:
df.loc[49003]

Row ID                                            38123
Order ID                       CA-2014-TC20980140-41915
Order Date                          2014-10-03 00:00:00
Ship Date                           2014-10-10 00:00:00
Ship Mode                                Standard Class
Customer ID                                TC-209801402
Customer Name                              Tamara Chand
Segment                                       Corporate
Postal Code                                     47905.0
City                                          Lafayette
State                                           Indiana
Country                                   United States
Region                                       Central US
Market                                             USCA
Product ID                                  TEC-CO-3691
Category                                     Technology
Sub-Category                                    Copiers
Product Name      Canon imageCLASS 2200 Advanced Copier
Sales                                          17499.95
Quantity                                              5
Discount                                            0.0
Profit                                         8399.976
Shipping Cost                                    349.07
Order Priority                                   Medium
Name: 49003, dtype: object

In [ ]:
df.groupby("Region")["Sales"].mean().sort_values(ascending=False)

Region
Eastern Asia         360.176660
Southern Asia        326.392722
Oceania              315.510356
Western Europe       294.395660
Northern Europe      288.919763
Southern Europe      288.023648
Southeastern Asia    282.653617
Southern US          241.803645
Eastern US           238.336110
Western US           226.493233
Central Africa       223.374821
Southern Africa      220.066444
Central America      217.788573
Central US           215.772661
South America        206.567496
Eastern Europe       202.768764
Caribbean            191.882166
North Africa         182.485610
Eastern Africa       175.626400
Canada               174.292109
Western Asia         129.961869
Western Africa       119.095077
Central Asia          88.992899
Name: Sales, dtype: float64

product with highest profit

In [ ]:
df["Profit"].nlargest(1)

49003    8399.976
Name: Profit, dtype: float64

In [ ]:
df[df["Profit"]==df["Profit"].max()]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
49003,38123,CA-2014-TC20980140-41915,2014-10-03,2014-10-10,Standard Class,TC-209801402,Tamara Chand,Corporate,47905.0,Lafayette,...,TEC-CO-3691,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.95,5,0.0,8399.976,349.07,Medium